language: php
php:
  - '7.3'
install:
  - composer install

before_script:
  - printf "\n" | pecl install yaml
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - composer require codacy/coverage

after_script:
  - ./cc-test-reporter format-coverage -t clover tests/clover.xml
  - ./cc-test-reporter upload-coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ./vendor/bin/codacycoverage clover tests/clover.xml
